questions = [
    'You have to optimize the padframe power rails for a mixed-signal design. Explain how you would allocate metal layers and via groups for ESD and core power separately.',
    'During IR analysis, you discover a localized IR hotspot near a macro boundary. How would you refine your power grid around that region?',
    'How do you plan for on-die decoupling budgets when switching between different power domains at runtime?',
    'Describe how to implement adaptive body bias alongside power gating to reduce leakage in standby modes.',
    'You need to validate power integrity across PVT corners. Outline your plan for corner-based IR drop analysis.',
    'Explain the role of substrate and ground network in your overall power integrity strategy.',
    'How would you design the power ring and power straps for an extreme temperature application with high current requirements?',
    'You see an EM violation at a via segment. How do you decide between adding parallel vias versus increasing metal width?',
    'Describe how to extract and plot a histogram of IR drop values across the chip to identify problematic regions.',
    'How would you use hierarchical power switch insertion to control power-up sequences in a multi-domain system?',
    'Explain the trade-offs between using power grids vs. stripes for a memory macro array.',
    'What steps do you take to prepare power nets for STA tools to ensure accurate noise-aware timing?',
    'Discuss how to simulate and analyze switching noise coupling into the power grid during simultaneous switching outcomes.',
    'How do you integrate bond-wire inductance effects into your power integrity analysis for package-level modeling?',
    'Describe the considerations when designing the on-chip power mesh for high-frequency decoupling vs. low-frequency bulk decoupling.',
    'Your design has an ultra-low power domain. Explain strategies to minimize wake-up latency from power gating.',
    'How would you handle multiple PDNs crossing each other at different hierarchy levels in the floorplan?',
    'Explain the process of adding macro-level decoupling caps in floorplanning to meet transient current demands.',
    'Describe how to use virtual voltage sources in your extraction deck to account for external VRM behavior.',
    'Outline how you would conduct a sign-off flow that includes EM/IR analysis, noise analysis, and post-route optimization.',
    'Write a TCL script to sweep decap capacitance values and record resulting IR drop metrics.',
    'Develop a TCL procedure to automatically patch and regenerate extraction decks after floorplan changes.',
    'Create a TCL command that renames all power nets following a hierarchical naming convention.',
    'Write a TCL script to batch-run power integrity analysis on multiple corners and collect CSV outputs.',
    'Implement a TCL function to compare two extraction reports and highlight differences in IR drop.',
]
