questions = [
    'Your design targets a high-performance CPU core with peak current density hotspots. Describe how you would segment the power grid to minimize IR drop and ensure robust distribution.',
    'During post-route extraction, you observe significant IR drop on the periphery of a macro. How would you adjust your power mesh to mitigate this issue without impacting routing resources?',
    'You need to implement dynamic voltage scaling for a power domain. Outline the key considerations in creating power gating cells, retention registers, and isolation logic.',
    'A SoC requires multiple voltage domains powered by on-chip LDOs. Explain how to design the power network to manage LDO output droop during load transients.',
    "You're integrating a large analog block into a digital power network. What strategies do you use to separate and isolate analog power rails while minimizing noise coupling?",
    'In a 7nm design, the metal resistivity increases. How would you adjust metal widths and layer usage in your power grid to compensate for increased resistance?',
    'Explain how you would perform hierarchical power network planning for a block-level IP to meet IR and EM constraints at top-level assembly.',
    'Given a list of estimated switching currents for each block, how would you budget decoupling capacitance across the chip to maintain stable supply voltage?',
    'During timing closure, you find that power-grids cause routing congestion. How do you balance power grid density with timing-driven routing requirements?',
    'Outline the process to perform on-chip electromigration analysis and identify metal layers most prone to EM violations.',
    'You need to implement voltage island floorplanning. Describe the steps to create power domains, place isolation cells, and connect domain entry/exit points.',
    'A foundry provides IR drop limits per metal layer. How do you incorporate these limits in your power analysis and sign-off steps.',
    'Explain how to insert FET-based power switches and design switch enabled paths for power-on/power-off sequences.',
    'Given both tapped and non-tapped decap insertion methods, how do you choose the right approach for high-frequency noise suppression?',
    'Describe how to set up and extract on-chip power integrity analysis using a toolchain of extraction, solver, and reporting.',
    'Explain the difference between static IR drop and dynamic IR drop, and how to simulate dynamic effects in extraction.',
    'Your design uses voltage droop simulation. How would you calibrate your model against silicon measurement data?',
    'Discuss the impact of via redundancy in the power grid and how adding or reducing vias affects EM and IR.',
    'How would you model temperature-dependent resistivity effects in your power integrity analysis?',
    'Explain how you would verify that the final power grid meets both EM current density limits and IR drop requirements under worst-case switching scenarios.',
    'Write a TCL script to parse the extraction report and list all nets with IR drop above 100mV.',
    'Write a TCL command sequence to insert decap cells around the highest switching block automatically.',
    'Develop a TCL procedure to export a CSV of power grid metal usage per layer.',
    'Create a TCL script that highlights all weak power nets (below a user-defined width) in the visualizer.',
    'Write a TCL function to automate running an EM check and summarizing violations in a log file.',
]
