questions = [
    'Your design integrates an on-chip voltage regulator. How do you model its output impedance in your power network?',
    'Describe how to plan for multi-drop power rails for a high-power GPU shader cluster.',
    'Explain how to budget decap capacitance for idle vs. active current profiles.',
    'Discuss the impact of differential PDNs for analog circuits and how to route them.',
    'How would you setup and measure power grid IR in a power-cycle simulation?',
    'Outline strategies for designing low-impedance paths for power distribution in chiplets.',
    'Explain how to handle cross-hierarchy power droop analysis in 3D IC stacks.',
    'How do you manage power integrity when mixing flip-chip and wire-bond packages?',
    'Describe the steps to perform real-time PDN monitoring using on-chip sensors.',
    'How would you design a redundant power path for safety-critical subsystems?',
    'Explain the concept of adaptive power scaling and how to integrate it into your PDN.',
    'Discuss trade-offs between stripe-based vs. mesh-based power distribution for low-power blocks.',
    'Outline how to plan for decap retention across ultra-low standby currents.',
    'How do you incorporate foundry PEX rules into your PDN planning?',
    'Explain how to analyze the impact of thermal effects on PDN resistivity.',
    'Describe how to run a noise-aware STA flow that includes PDN coupling effects.',
    'How would you use virtual ground islands to trap noise in mixed-signal designs?',
    'Explain how to construct an on-chip LDO and integrate it into the PDN.',
    'Outline the process to prepare PDN documentation for a design review.',
    'Discuss strategies to mitigate simultaneous switching noise in large arrays.',
    'Write a TCL script to calculate and plot via-level current density from extraction data.',
    'Develop a TCL procedure to add guard bands around critical power nets.',
    'Create a TCL command that automates conversion of floorplan decap placement to extraction deck entries.',
    'Write a TCL function to batch-update hierarchical netlist power net names.',
    'Implement a TCL script to generate a summary PDF of power analysis reports.',
]
