questions = [
    'Your project requires dual VDD rails for analog and digital sections. How do you ensure proper isolation and minimal coupling?',
    'During sign-off, you find that the power grid on M6 layer is under-utilized. How would you rebalance grid density across layers?',
    'Explain the process of designing a decoupling network that meets both high-frequency and low-frequency noise requirements.',
    'How do you incorporate package parasitics into your on-chip power network analysis?',
    'Given a voltage droop violation, outline the steps to identify the root cause using hierarchical debug.',
    'How would you adjust power routing if you see a high IR drop only under worst negative slack test conditions?',
    'Discuss strategies for floorplanning macro power domains to minimize domain crossing congestion.',
    'Explain how to allocate power mesh resources for a memory array with high switching activity.',
    'How do you design retention flip-flops and control logic for state retention during power-down?',
    'In a safety-critical application, what additional power integrity checks would you introduce?',
    'Describe how to perform dynamic EM analysis for multi-cycle switching events.',
    'Your power mesh shows significant variation between extracted and simulated data. How do you calibrate extraction parameters?',
    'Explain how to design a power network that supports multi-voltage corners for dynamic voltage scaling.',
    'How would you implement a debug mechanism to visualize IR hotspots in the layout tool?',
    'Discuss how to manage decap distribution in non-uniform block densities.',
    'Explain the importance of via redundancy strategies in high-current paths.',
    'How do you ensure ESD ring design does not interfere with core power straps?',
    'Describe how to prepare and submit power sign-off scripts for the final sign-off meeting.',
    'How would you approach on-chip power network design for a high-speed SerDes lane requiring clean supply?',
    'Explain how to analyze hold-up time of decoupling capacitors during glitch scenarios.',
    'Write a TCL script to automatically generate a corner-based IR drop report with annotations.',
    'Develop a TCL procedure to insert isolation cells in nets crossing power domains.',
    'Create a TCL command that visualizes EM hotspots by drawing colored markers on the layout.',
    'Write a TCL function to export viewports of the weakest power net to image files.',
    'Implement a TCL script to update power grid width parameters based on CSV input.',
]
